# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostgames', '0010_auto_20160524_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('view_unmoderated_comment', 'Can view unmoderated comments'), ('moderate_comment', 'Can moderate comments'))},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': (('view_unshown_Game', 'Can see games that have not been shown.'),)},
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostgames.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostgames.Game'),
        ),
    ]
