# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('plot_summary', models.TextField()),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
