# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lostgames', '0009_auto_20160523_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=256)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='is_shown',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostgames.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('STEALTH', 'Stealth'), ('FPS', 'First-Person Shooter'), ('PUZZLE', 'Puzzle'), ('SIM', 'Simulator'), ('OPEN_WORLD', 'Open World'), ('RPG', 'Role-Playing Game'), ('JRPG', 'Japanese Role-Playing Game'), ('STRATEGY', 'Strategy'), ('MMO', 'Massively Mutliplayer OnLine'), ('PLATFORM', 'Platform'), ('MOBA', 'Mutliplayer Online Battle Arena'), ('INDIE', 'Indie')], default='Adventure', max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostgames.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='box_art',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_art', to='lostgames.Photo'),
        ),
    ]
